[
    {
        "RBID": "rb-oablfkpnv",
        "COMPANY_NAME": "Medpace",
        "DOMAIN": "medpace.com",
        "LOCATION_CITY": "Cincinnati",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Medpace",
        "company_city": "Cincinnati",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 20000,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health, 2023 hospital report",
    },
    {
        "RBID": "rb-oacfwnl3e",
        "COMPANY_NAME": "Aultman Health Foundation",
        "DOMAIN": "aultman.org",
        "LOCATION_CITY": "Canton",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Aultman Health Foundation",
        "company_city": "Canton",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 200,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health, 2023 hospital statistics report",
    },
    {
        "RBID": "rb-oacjkn2r5",
        "COMPANY_NAME": "The Christ Hospital Health Network",
        "DOMAIN": "thechristhospital.com",
        "LOCATION_CITY": "Cincinnati",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "The Christ Hospital Health Network",
        "company_city": "Cincinnati",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 500,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health, 2023 hospital bed report",
    },
    {
        "RBID": "rb-oacdnzs2k",
        "COMPANY_NAME": "Akron Children's Hospital",
        "DOMAIN": "akronchildrens.org",
        "LOCATION_CITY": "Akron",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 2,
        "company_name": "Akron Children's Hospital",
        "company_city": "Akron",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 400,
        "source_hospitals_number_of_beds_ohio": "2023 Ohio Department of Health hospital report",
    },
    {
        "RBID": "rb-oaclp34zr",
        "COMPANY_NAME": "Health Alliance",
        "DOMAIN": "uchealth.com",
        "LOCATION_CITY": "Cincinnati",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 7,
        "company_name": "Health Alliance",
        "company_city": "Cincinnati",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 200,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health, 2023 hospital bed report",
    },
    {
        "RBID": "rb-oacvgfmkb",
        "COMPANY_NAME": "The Metrohealth System Cleveland, Oh",
        "DOMAIN": "metrohealth.org",
        "LOCATION_CITY": "Cleveland",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "The Metrohealth System Cleveland, Oh",
        "company_city": "Cleveland",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 200,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health 2023 hospital report",
    },
    {
        "RBID": "rb-oacdiskoy",
        "COMPANY_NAME": "Children's Hospital Medical Center Of Akron",
        "DOMAIN": "akronchildrens.org",
        "LOCATION_CITY": "Akron",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Children's Hospital Medical Center Of Akron",
        "company_city": "Akron",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 200,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health, 2023 hospital bed report",
    },
    {
        "RBID": "rb-oabhgkfpc",
        "COMPANY_NAME": "Itw Food Equipment Group",
        "DOMAIN": "itwfoodequipment.com",
        "LOCATION_CITY": "Troy",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 2,
        "company_name": "Itw Food Equipment Group",
        "company_city": "Troy",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 200,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health, 2023 hospital report",
    },
    {
        "RBID": "rb-oadlemur6",
        "COMPANY_NAME": "Summa Health",
        "DOMAIN": "summahealth.org",
        "LOCATION_CITY": "Akron",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Summa Health",
        "company_city": "Akron",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 100,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health hospital data report, 2023-09",
    },
    {
        "RBID": "rb-oabg6ez34",
        "COMPANY_NAME": "Cwru Regenerative Medicine & Entrepreneurship Program Rgme",
        "DOMAIN": "case.edu",
        "LOCATION_CITY": "Cleveland",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Cwru Regenerative Medicine & Entrepreneurship Program Rgme",
        "company_city": "Cleveland",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 200,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health 2023 Hospital Report",
    },
    {
        "RBID": "rb-oackxmqv5",
        "COMPANY_NAME": "Dayton Children's Hospital",
        "DOMAIN": "childrensdayton.org",
        "LOCATION_CITY": "Dayton",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Dayton Children's Hospital",
        "company_city": "Dayton",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 200,
        "source_hospitals_number_of_beds_ohio": "2023 Ohio Department of Health hospital report",
    },
    {
        "RBID": "rb-oadgk4bce",
        "COMPANY_NAME": "Fairfield Medical Center",
        "DOMAIN": "fmchealth.org",
        "LOCATION_CITY": "Lancaster",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Fairfield Medical Center",
        "company_city": "Lancaster",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 100,
        "source_hospitals_number_of_beds_ohio": "2023 Ohio Department of Health hospital report",
    },
    {
        "RBID": "rb-oabjq2li7",
        "COMPANY_NAME": "Mobile Instrument Service & Repair",
        "DOMAIN": "agilitihealth.com",
        "LOCATION_CITY": "Bellefontaine",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Mobile Instrument Service & Repair",
        "company_city": "Bellefontaine",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 200,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health, 2023 hospital report",
    },
    {
        "RBID": "rb-oac3jngtp",
        "COMPANY_NAME": "Memorial Health System - Ohio",
        "DOMAIN": "mhsystem.org",
        "LOCATION_CITY": "Marietta",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Memorial Health System - Ohio",
        "company_city": "Marietta",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 200,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health, 2023 hospital bed report",
    },
    {
        "RBID": "rb-oacq2fup7",
        "COMPANY_NAME": "Memorial Health Ohio",
        "DOMAIN": "memorialohio.com",
        "LOCATION_CITY": "Marysville",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "company_name": "Memorial Health Ohio",
        "company_city": "Marysville",
        "company_state": "OH",
        "hospitals_number_of_beds_ohio": 25,
        "source_hospitals_number_of_beds_ohio": "Ohio Department of Health, 2023 hospital data report",
    },
]
