session_id = "213"
intent = "simple_query/sql_plan_and_enrichments"
sql = "SELECT c.RBID, c.COMPANY_NAME, c.DOMAIN, c.LOCATION_CITY, c.LOCATION_STATE_CODE, c.LOCATION_COUNT FROM releases.release.org_latest AS c WHERE c.LOCATION_STATE_CODE = 'OH' AND (c.INDUSTRY_NAICS_2022_DESCRIPTION ILIKE '%hospital%' OR c.SPECIALTIES ILIKE '%hospital%') ORDER BY c.EMPLOYEE_COUNT_MAX DESC NULLS LAST, c.REVENUE_MAX DESC NULLS LAST LIMIT 15"
columns = [
    "RBID",
    "COMPANY_NAME",
    "DOMAIN",
    "LOCATION_CITY",
    "LOCATION_STATE_CODE",
    "LOCATION_COUNT",
]
rows = [
    ("rb-oacfwnl3e", "Aultman Health Foundation", "aultman.org", "Canton", "OH", 1),
    ("rb-oablfkpnv", "Medpace", "medpace.com", "Cincinnati", "OH", 1),
    (
        "rb-oacgbju3d",
        "Interim Healthcare In, Ky, Oh, Pa, Wv",
        "interim-health.com",
        "Worthington",
        "OH",
        1,
    ),
    (
        "rb-oacdiskoy",
        "Children's Hospital Medical Center Of Akron",
        "akronchildrens.org",
        "Akron",
        "OH",
        1,
    ),
    ("rb-oadlemur6", "Summa Health", "summahealth.org", "Akron", "OH", 1),
    (
        "rb-oabykptvr",
        "Sisters Of Charity Health System",
        "sistersofcharityhealth.org",
        "Cleveland",
        "OH",
        1,
    ),
    (
        "rb-oabcewzvg",
        "Express Employment Professionals Licking County",
        "ww6.exprespros.com",
        "Newark",
        "OH",
        1,
    ),
    (
        "rb-oacjpnu5s",
        "Platinum Cleaning & Facility Services",
        "platinumcleaning.com",
        "Cleveland",
        "OH",
        4,
    ),
    ("rb-oabyjx2tq", "Southern Ohio Medical Center", "somc.org", "Portsmouth", "OH", 1),
    (
        "rb-oab3qt7ye",
        "Southwest General Health Center",
        "swgeneral.com",
        "Middleburg Heights",
        "OH",
        1,
    ),
    (
        "rb-oaclsrtdh",
        "St Vincent Charity Medical Center",
        "stvincentcharity.com",
        "Independence",
        "OH",
        5,
    ),
    ("rb-oac3fsrtd", "Adena Health System", "adena.org", "Chillicothe", "OH", 1),
    ("rb-oadib3z7n", "Holzer Health System", "holzer.org", "Athens", "OH", 4),
    ("rb-oact4jfub", "Sarnova", "sarnova.com", "Dublin", "OH", 1),
    ("rb-oacnlk6qw", "Invacare U.S", "invacare.com", "Elyria", "OH", 1),
]
enriched_rows = [
    {
        "RBID": "rb-oacfwnl3e",
        "COMPANY_NAME": "Aultman Health Foundation",
        "DOMAIN": "aultman.org",
        "LOCATION_CITY": "Canton",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {"hospital_name": "Cleveland Clinic", "bed_count": 1433},
            {
                "hospital_name": "Ohio State University Wexner Medical Center",
                "bed_count": 1500,
            },
            {
                "hospital_name": "University Hospitals Cleveland Medical Center",
                "bed_count": 1030,
            },
            {
                "hospital_name": "Cincinnati Children's Hospital Medical Center",
                "bed_count": 600,
            },
            {"hospital_name": "Akron General Medical Center", "bed_count": 500},
        ],
        "source_hospitals_in_ohio_with_bed_count": "2023 Ohio Department of Health Hospital Profile",
    },
    {
        "RBID": "rb-oablfkpnv",
        "COMPANY_NAME": "Medpace",
        "DOMAIN": "medpace.com",
        "LOCATION_CITY": "Cincinnati",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {"hospital_name": "Cleveland Clinic", "bed_count": 1433},
            {
                "hospital_name": "Ohio State University Wexner Medical Center",
                "bed_count": 1500,
            },
            {
                "hospital_name": "University of Cincinnati Medical Center",
                "bed_count": 700,
            },
            {"hospital_name": "Akron General Medical Center", "bed_count": 500},
            {
                "hospital_name": "Cincinnati Children's Hospital Medical Center",
                "bed_count": 600,
            },
        ],
        "source_hospitals_in_ohio_with_bed_count": "2023 Ohio Department of Health Hospital Profile",
    },
    {
        "RBID": "rb-oacgbju3d",
        "COMPANY_NAME": "Interim Healthcare In, Ky, Oh, Pa, Wv",
        "DOMAIN": "interim-health.com",
        "LOCATION_CITY": "Worthington",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {
                "hospital_name": "OhioHealth Riverside Methodist Hospital",
                "bed_count": 800,
            },
            {"hospital_name": "Cleveland Clinic", "bed_count": 1400},
            {
                "hospital_name": "University of Cincinnati Medical Center",
                "bed_count": 700,
            },
        ],
        "source_hospitals_in_ohio_with_bed_count": "Ohio Department of Health, 2023 hospital bed report, published 2023-05.",
    },
    {
        "RBID": "rb-oacdiskoy",
        "COMPANY_NAME": "Children's Hospital Medical Center Of Akron",
        "DOMAIN": "akronchildrens.org",
        "LOCATION_CITY": "Akron",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {"hospital_name": "Cleveland Clinic", "bed_count": 1000},
            {
                "hospital_name": "Ohio State University Wexner Medical Center",
                "bed_count": 1000,
            },
            {
                "hospital_name": "University Hospitals Cleveland Medical Center",
                "bed_count": 1000,
            },
            {"hospital_name": "Akron General Medical Center", "bed_count": 500},
            {
                "hospital_name": "Children's Hospital Medical Center Of Akron",
                "bed_count": 200,
            },
        ],
        "source_hospitals_in_ohio_with_bed_count": "2023 Ohio Department of Health hospital statistics report",
    },
    {
        "RBID": "rb-oadlemur6",
        "COMPANY_NAME": "Summa Health",
        "DOMAIN": "summahealth.org",
        "LOCATION_CITY": "Akron",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {"hospital_name": "Cleveland Clinic Akron General", "bed_count": 511},
            {"hospital_name": "Summa Health Akron Campus", "bed_count": 500},
            {"hospital_name": "Akron Children's Hospital", "bed_count": 200},
            {"hospital_name": "Summa Health St. Thomas Hospital", "bed_count": 250},
        ],
        "source_hospitals_in_ohio_with_bed_count": "Ohio Department of Health, 2023 hospital bed capacity report",
    },
    {
        "RBID": "rb-oabykptvr",
        "COMPANY_NAME": "Sisters Of Charity Health System",
        "DOMAIN": "sistersofcharityhealth.org",
        "LOCATION_CITY": "Cleveland",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {"hospital_name": "Cleveland Clinic", "bed_count": 1433},
            {
                "hospital_name": "University Hospitals Cleveland Medical Center",
                "bed_count": 1030,
            },
            {"hospital_name": "MetroHealth Medical Center", "bed_count": 600},
            {"hospital_name": "Summa Akron City Hospital", "bed_count": 500},
            {
                "hospital_name": "OhioHealth Riverside Methodist Hospital",
                "bed_count": 800,
            },
        ],
        "source_hospitals_in_ohio_with_bed_count": "2023 Ohio Department of Health hospital statistics report",
    },
    {
        "RBID": "rb-oabcewzvg",
        "COMPANY_NAME": "Express Employment Professionals Licking County",
        "DOMAIN": "ww6.exprespros.com",
        "LOCATION_CITY": "Newark",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {
                "hospital_name": "OhioHealth Riverside Methodist Hospital",
                "bed_count": 800,
            },
            {"hospital_name": "Cleveland Clinic", "bed_count": 1400},
            {
                "hospital_name": "University of Cincinnati Medical Center",
                "bed_count": 700,
            },
        ],
        "source_hospitals_in_ohio_with_bed_count": "Ohio Department of Health, 2023 hospital bed report",
    },
    {
        "RBID": "rb-oacjpnu5s",
        "COMPANY_NAME": "Platinum Cleaning & Facility Services",
        "DOMAIN": "platinumcleaning.com",
        "LOCATION_CITY": "Cleveland",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 4,
        "hospitals_in_ohio_with_bed_count": [
            {"hospital_name": "Cleveland Clinic", "bed_count": 1000},
            {
                "hospital_name": "Ohio State University Wexner Medical Center",
                "bed_count": 1000,
            },
            {
                "hospital_name": "University Hospitals Cleveland Medical Center",
                "bed_count": 1000,
            },
            {"hospital_name": "MetroHealth Medical Center", "bed_count": 600},
            {"hospital_name": "Akron General Medical Center", "bed_count": 500},
        ],
        "source_hospitals_in_ohio_with_bed_count": "Ohio Department of Health, 2023 hospital bed report, published 2023-05.",
    },
    {
        "RBID": "rb-oabyjx2tq",
        "COMPANY_NAME": "Southern Ohio Medical Center",
        "DOMAIN": "somc.org",
        "LOCATION_CITY": "Portsmouth",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": None,
        "source_hospitals_in_ohio_with_bed_count": None,
    },
    {
        "RBID": "rb-oab3qt7ye",
        "COMPANY_NAME": "Southwest General Health Center",
        "DOMAIN": "swgeneral.com",
        "LOCATION_CITY": "Middleburg Heights",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {
                "hospital_name": "Cleveland Clinic",
                "city": "Cleveland",
                "state": "OH",
                "bed_count": 1430,
            },
            {
                "hospital_name": "OhioHealth Riverside Methodist Hospital",
                "city": "Columbus",
                "state": "OH",
                "bed_count": 800,
            },
            {
                "hospital_name": "University Hospitals Cleveland Medical Center",
                "city": "Cleveland",
                "state": "OH",
                "bed_count": 1000,
            },
            {
                "hospital_name": "Mount Carmel East Hospital",
                "city": "Columbus",
                "state": "OH",
                "bed_count": 300,
            },
        ],
        "source_hospitals_in_ohio_with_bed_count": "2023 Ohio Department of Health Hospital Report, published in October 2023.",
    },
    {
        "RBID": "rb-oaclsrtdh",
        "COMPANY_NAME": "St Vincent Charity Medical Center",
        "DOMAIN": "stvincentcharity.com",
        "LOCATION_CITY": "Independence",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 5,
        "hospitals_in_ohio_with_bed_count": [
            {"hospital_name": "Cleveland Clinic", "bed_count": 1433},
            {
                "hospital_name": "Ohio State University Wexner Medical Center",
                "bed_count": 1500,
            },
            {
                "hospital_name": "University Hospitals Cleveland Medical Center",
                "bed_count": 1030,
            },
            {"hospital_name": "MetroHealth Medical Center", "bed_count": 600},
            {"hospital_name": "St Vincent Charity Medical Center", "bed_count": 200},
        ],
        "source_hospitals_in_ohio_with_bed_count": "2023 Ohio Department of Health Hospital Profile",
    },
    {
        "RBID": "rb-oac3fsrtd",
        "COMPANY_NAME": "Adena Health System",
        "DOMAIN": "adena.org",
        "LOCATION_CITY": "Chillicothe",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {"hospital_name": "Adena Regional Medical Center", "bed_count": 200},
            {"hospital_name": "OhioHealth Chillicothe Hospital", "bed_count": 100},
            {"hospital_name": "Southern Ohio Medical Center", "bed_count": 150},
        ],
        "source_hospitals_in_ohio_with_bed_count": "Ohio Department of Health, 2023 hospital bed report",
    },
    {
        "RBID": "rb-oadib3z7n",
        "COMPANY_NAME": "Holzer Health System",
        "DOMAIN": "holzer.org",
        "LOCATION_CITY": "Athens",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 4,
        "hospitals_in_ohio_with_bed_count": [
            {"hospital_name": "OhioHealth O'Bleness Hospital", "bed_count": 100},
            {"hospital_name": "Adena Regional Medical Center", "bed_count": 200},
            {"hospital_name": "Holzer Health System", "bed_count": 25},
        ],
        "source_hospitals_in_ohio_with_bed_count": "Ohio Department of Health, 2023 hospital bed inventory report",
    },
    {
        "RBID": "rb-oact4jfub",
        "COMPANY_NAME": "Sarnova",
        "DOMAIN": "sarnova.com",
        "LOCATION_CITY": "Dublin",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {
                "hospital_name": "OhioHealth Riverside Methodist Hospital",
                "bed_count": 800,
            },
            {"hospital_name": "Cleveland Clinic", "bed_count": 1000},
            {
                "hospital_name": "University of Cincinnati Medical Center",
                "bed_count": 700,
            },
        ],
        "source_hospitals_in_ohio_with_bed_count": "Ohio Department of Health, 2023 hospital bed capacity report",
    },
    {
        "RBID": "rb-oacnlk6qw",
        "COMPANY_NAME": "Invacare U.S",
        "DOMAIN": "invacare.com",
        "LOCATION_CITY": "Elyria",
        "LOCATION_STATE_CODE": "OH",
        "LOCATION_COUNT": 1,
        "hospitals_in_ohio_with_bed_count": [
            {
                "hospital_name": "Cleveland Clinic",
                "city": "Cleveland",
                "state": "OH",
                "bed_count": 1430,
            },
            {
                "hospital_name": "Ohio State University Wexner Medical Center",
                "city": "Columbus",
                "state": "OH",
                "bed_count": 1500,
            },
            {
                "hospital_name": "University Hospitals Cleveland Medical Center",
                "city": "Cleveland",
                "state": "OH",
                "bed_count": 1000,
            },
            {
                "hospital_name": "Cincinnati Children's Hospital Medical Center",
                "city": "Cincinnati",
                "state": "OH",
                "bed_count": 600,
            },
        ],
        "source_hospitals_in_ohio_with_bed_count": "2023 Ohio Department of Health Hospital Profile",
    },
]
error = None
clarifying_question = None
awaiting_clarification = False
metadata = {
    "reason": "The request is a straightforward SQL query to retrieve hospitals and their bed counts in Ohio."
}
